### PR TITLE
[WIP] Fix default value of a collection when available items comes from a source

### PR DESCRIPTION
**Pull request by tdesvenain**
refs issue #59

### CODE REVIEW

**Comment by tdesvenain** [comment]
Hi, before cleaning up this implementation and adding tests, i'd like to get your opinion about the way i fix the issue.

**Comment by icemac** [comment]
@tdesvenain Sorry, I do not understand the problem. Maybe a test could show what you want to achieve. (BTW I am using sources instead of vocabularies all the time.)

**Comment by icemac** [comment]
@tdesvenain What is the current status of this PR?

**Comment by tdesvenain** [comment]
I have to write the unit tests

**Comment by icemac** [comment]
@tdesvenain wrote:
> I have to write the unit tests

Okay, nice. Please ask if you have questions about the tests.

**Comment by icemac** [comment]
@tdesvenain Could you please rebase on master, too, so we get coverage measurement for this PR.

**Comment by icemac** [comment]
@tdesvenain I redirected the PR to the new `3.x` branch, as I closed `3.2.x` in favour of it.

**Comment by icemac** [comment]
Is this PR still valid or should we close it?

**Pull request closed without merging**
