### PR TITLE
Add Traditional Chinese Translation.

### PR DESCRIPTION
**Pull request by l34marr**

### CODE REVIEW

**Comment by mgedmin** [comment]
Thank you!

IANAL, but I think translations are copyrightable, which means you have to sign the Zope Foundation Committer Agreement before we can merge them: http://foundation.zope.org/agreements

**Comment by l34marr** [comment]
I attached the signed Contributor Agreement to you and contributor-admin@zope.org on Mar 25. Please let me know if anything else needed.

**Comment by mauritsvanrees** [comment]
@l34marr Can you resend your contributor agreement contributor-admin@zope.org? Andreas is looking at agreements now but cannot find it.

**Comment by l34marr** [comment]
I believe Andreas already see my agreements, and he has added me as collaborator. If this pull request is OK, @mauritsvanrees can you help to merge it? Or, does it mean I can merge my own translation work? I only have experience on Plone collective/plone.app.locales and would love to know more practice here. Thanks.

**Comment by mauritsvanrees** [comment]
Great. I will merge it.
Since you can now commit directly to the zopefoundation repositories, I would say the same rules apply as for Plone repos. For translations I would say: just commit them directly, without pull request.

**Comment by mauritsvanrees** [comment]
I have released z3c.form 3.2.6 with your translations. Thanks!

**Pull request merged**
